# Generated by Django 3.0 on 2019-12-07 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatLongAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(default='')),
                ('latitude', models.CharField(max_length=60)),
                ('longitude', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
